acme_hello_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
counting:
    pattern: /counting/{from}/{to}
    defaults: { _controller: AcmeHelloBundle:Default:counting }