fantasygame_team_homepage:
    pattern:  /
    defaults: { _controller: FantasygameTeamBundle:Campaign:index }
fantasygame_campaign_edit:
    pattern:  /edit/{id}
    defaults: { _controller: FantasygameTeamBundle:Campaign:editCampaign, id: 0 }
fantasygame_campaign_remove:
    pattern:  /remove/{id}
    defaults: { _controller: FantasygameTeamBundle:Campaign:removeCampaign}
